// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrnemqrhwxpajsmhymyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybmVtcXJod3hwYWpzbWh5bXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDM5ODksImV4cCI6MjA1OTQxOTk4OX0.0vCjK5eo0Qxpp5wWytXPHAv6mp0Iw1CD9fZXlrW_9ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);