// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzqwafbznljymqixgfsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cXdhZmJ6bmxqeW1xaXhnZnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTc5ODgsImV4cCI6MjA1OTQ5Mzk4OH0.SLkZMAGp7mmXfcYtF3SVZEIpy7AXi02oATEHHYs-SMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);